INSERT INTO PERSONAL_INFO (PERSONAL_INFO_ID, NAME, PASSWORD, EMAIL, NPC)
    VALUES ('5', 'Potolea', '123456', 'potolea@yahoo.com', '5000000999999');
INSERT INTO ADDRESS (ADDRESS_ID, STREET, CITY, COUNTRY, POSTAL_CODE,PERSONAL_INFO_ID) VALUES ('5', 'Baritiu, 1', 'Cluj-Napoca', 'Romania', '545200','5');

INSERT INTO TEACHER (TEACHER_ID, PERSONAL_INFO_ID, ENTITLING) VALUES ('2', '5', 'Profesor universitar');

INSERT INTO TEACHER_TOPIC (TEACHER_ID, TOPIC_ID) VALUES ('2', '2');